-- Step 1: 连接三个表（订单、订单明细、产品信息）
WITH joined_data AS (
  SELECT
    o.o_order_id,
    o.date,
    li.quantity,
    li.trip_type,  -- 如果没有标签，则此字段可不选
    p.department
  FROM orders o
  JOIN lineitem li ON o.o_order_id = li.li_order_id
  JOIN product p ON li.li_product_id = p.p_product_id
),

-- Step 2: 按订单聚合扫描数量、绝对扫描数量以及标签（取每个订单中 trip_type 的最小值，假设每个订单只有一个标签）
agg_counts AS (
  SELECT
    o_order_id,
    SUM(quantity) AS scan_count,
    SUM(ABS(quantity)) AS scan_count_abs,
    MIN(trip_type) AS trip_type
  FROM joined_data
  GROUP BY o_order_id
),

-- Step 3: 生成每个订单对应的星期指标
-- 如果该订单中存在某一天（如 Monday）的记录，则该列取 1，否则为 0
weekday_pivot AS (
  SELECT
    o_order_id,
    MAX(CASE WHEN DAYNAME(date) = 'Monday' THEN 1 ELSE 0 END) AS Monday,
    MAX(CASE WHEN DAYNAME(date) = 'Tuesday' THEN 1 ELSE 0 END) AS Tuesday,
    MAX(CASE WHEN DAYNAME(date) = 'Wednesday' THEN 1 ELSE 0 END) AS Wednesday,
    MAX(CASE WHEN DAYNAME(date) = 'Thursday' THEN 1 ELSE 0 END) AS Thursday,
    MAX(CASE WHEN DAYNAME(date) = 'Friday' THEN 1 ELSE 0 END) AS Friday,
    MAX(CASE WHEN DAYNAME(date) = 'Saturday' THEN 1 ELSE 0 END) AS Saturday,
    MAX(CASE WHEN DAYNAME(date) = 'Sunday' THEN 1 ELSE 0 END) AS Sunday
  FROM joined_data
  GROUP BY o_order_id
),

-- Step 4: 按部门对每个订单的扫描数量进行聚合
-- 下面列出了所有要求的部门，如未出现的部门后续将用 0 填充
dept_pivot AS (
  SELECT
    o_order_id,
    SUM(CASE WHEN department = 'FINANCIAL SERVICES' THEN quantity ELSE 0 END) AS "FINANCIAL SERVICES",
    SUM(CASE WHEN department = 'SHOES' THEN quantity ELSE 0 END) AS SHOES,
    SUM(CASE WHEN department = 'PERSONAL CARE' THEN quantity ELSE 0 END) AS "PERSONAL CARE",
    SUM(CASE WHEN department = 'PAINT AND ACCESSORIES' THEN quantity ELSE 0 END) AS "PAINT AND ACCESSORIES",
    SUM(CASE WHEN department = 'DSD GROCERY' THEN quantity ELSE 0 END) AS "DSD GROCERY",
    SUM(CASE WHEN department = 'MEAT - FRESH & FROZEN' THEN quantity ELSE 0 END) AS "MEAT - FRESH & FROZEN",
    SUM(CASE WHEN department = 'DAIRY' THEN quantity ELSE 0 END) AS DAIRY,
    SUM(CASE WHEN department = 'PETS AND SUPPLIES' THEN quantity ELSE 0 END) AS "PETS AND SUPPLIES",
    SUM(CASE WHEN department = 'HOUSEHOLD CHEMICALS/SUPP' THEN quantity ELSE 0 END) AS "HOUSEHOLD CHEMICALS/SUPP",
    SUM(CASE WHEN department = 'IMPULSE MERCHANDISE' THEN quantity ELSE 0 END) AS "IMPULSE MERCHANDISE",
    SUM(CASE WHEN department = 'PRODUCE' THEN quantity ELSE 0 END) AS PRODUCE,
    SUM(CASE WHEN department = 'CANDY, TOBACCO, COOKIES' THEN quantity ELSE 0 END) AS "CANDY, TOBACCO, COOKIES",
    SUM(CASE WHEN department = 'GROCERY DRY GOODS' THEN quantity ELSE 0 END) AS "GROCERY DRY GOODS",
    SUM(CASE WHEN department = 'BOYS WEAR' THEN quantity ELSE 0 END) AS "BOYS WEAR",
    SUM(CASE WHEN department = 'FABRICS AND CRAFTS' THEN quantity ELSE 0 END) AS "FABRICS AND CRAFTS",
    SUM(CASE WHEN department = 'JEWELRY AND SUNGLASSES' THEN quantity ELSE 0 END) AS "JEWELRY AND SUNGLASSES",
    SUM(CASE WHEN department = 'MENS WEAR' THEN quantity ELSE 0 END) AS "MENS WEAR",
    SUM(CASE WHEN department = 'ACCESSORIES' THEN quantity ELSE 0 END) AS ACCESSORIES,
    SUM(CASE WHEN department = 'HOME MANAGEMENT' THEN quantity ELSE 0 END) AS "HOME MANAGEMENT",
    SUM(CASE WHEN department = 'FROZEN FOODS' THEN quantity ELSE 0 END) AS "FROZEN FOODS",
    SUM(CASE WHEN department = 'SERVICE DELI' THEN quantity ELSE 0 END) AS "SERVICE DELI",
    SUM(CASE WHEN department = 'INFANT CONSUMABLE HARDLINES' THEN quantity ELSE 0 END) AS "INFANT CONSUMABLE HARDLINES",
    SUM(CASE WHEN department = 'PRE PACKED DELI' THEN quantity ELSE 0 END) AS "PRE PACKED DELI",
    SUM(CASE WHEN department = 'COOK AND DINE' THEN quantity ELSE 0 END) AS "COOK AND DINE",
    SUM(CASE WHEN department = 'PHARMACY OTC' THEN quantity ELSE 0 END) AS "PHARMACY OTC",
    SUM(CASE WHEN department = 'LADIESWEAR' THEN quantity ELSE 0 END) AS LADIESWEAR,
    SUM(CASE WHEN department = 'COMM BREAD' THEN quantity ELSE 0 END) AS "COMM BREAD",
    SUM(CASE WHEN department = 'BAKERY' THEN quantity ELSE 0 END) AS BAKERY,
    SUM(CASE WHEN department = 'HOUSEHOLD PAPER GOODS' THEN quantity ELSE 0 END) AS "HOUSEHOLD PAPER GOODS",
    SUM(CASE WHEN department = 'CELEBRATION' THEN quantity ELSE 0 END) AS CELEBRATION,
    SUM(CASE WHEN department = 'HARDWARE' THEN quantity ELSE 0 END) AS HARDWARE,
    SUM(CASE WHEN department = 'BEAUTY' THEN quantity ELSE 0 END) AS BEAUTY,
    SUM(CASE WHEN department = 'AUTOMOTIVE' THEN quantity ELSE 0 END) AS AUTOMOTIVE,
    SUM(CASE WHEN department = 'BOOKS AND MAGAZINES' THEN quantity ELSE 0 END) AS "BOOKS AND MAGAZINES",
    SUM(CASE WHEN department = 'SEAFOOD' THEN quantity ELSE 0 END) AS SEAFOOD,
    SUM(CASE WHEN department = 'OFFICE SUPPLIES' THEN quantity ELSE 0 END) AS "OFFICE SUPPLIES",
    SUM(CASE WHEN department = 'LAWN AND GARDEN' THEN quantity ELSE 0 END) AS "LAWN AND GARDEN",
    SUM(CASE WHEN department = 'SHEER HOSIERY' THEN quantity ELSE 0 END) AS "SHEER HOSIERY",
    SUM(CASE WHEN department = 'WIRELESS' THEN quantity ELSE 0 END) AS WIRELESS,
    SUM(CASE WHEN department = 'BEDDING' THEN quantity ELSE 0 END) AS BEDDING,
    SUM(CASE WHEN department = 'BATH AND SHOWER' THEN quantity ELSE 0 END) AS "BATH AND SHOWER",
    SUM(CASE WHEN department = 'HORTICULTURE AND ACCESS' THEN quantity ELSE 0 END) AS "HORTICULTURE AND ACCESS",
    SUM(CASE WHEN department = 'HOME DECOR' THEN quantity ELSE 0 END) AS "HOME DECOR",
    SUM(CASE WHEN department = 'TOYS' THEN quantity ELSE 0 END) AS TOYS,
    SUM(CASE WHEN department = 'INFANT APPAREL' THEN quantity ELSE 0 END) AS "INFANT APPAREL",
    SUM(CASE WHEN department = 'LADIES SOCKS' THEN quantity ELSE 0 END) AS "LADIES SOCKS",
    SUM(CASE WHEN department = 'PLUS AND MATERNITY' THEN quantity ELSE 0 END) AS "PLUS AND MATERNITY",
    SUM(CASE WHEN department = 'ELECTRONICS' THEN quantity ELSE 0 END) AS ELECTRONICS,
    SUM(CASE WHEN department = 'GIRLS WEAR, 4-6X  AND 7-14' THEN quantity ELSE 0 END) AS "GIRLS WEAR, 4-6X  AND 7-14",
    SUM(CASE WHEN department = 'BRAS & SHAPEWEAR' THEN quantity ELSE 0 END) AS "BRAS & SHAPEWEAR",
    SUM(CASE WHEN department = 'LIQUOR,WINE,BEER' THEN quantity ELSE 0 END) AS "LIQUOR,WINE,BEER",
    SUM(CASE WHEN department = 'SLEEPWEAR/FOUNDATIONS' THEN quantity ELSE 0 END) AS "SLEEPWEAR/FOUNDATIONS",
    SUM(CASE WHEN department = 'CAMERAS AND SUPPLIES' THEN quantity ELSE 0 END) AS "CAMERAS AND SUPPLIES",
    SUM(CASE WHEN department = 'SPORTING GOODS' THEN quantity ELSE 0 END) AS "SPORTING GOODS",
    SUM(CASE WHEN department = 'PLAYERS AND ELECTRONICS' THEN quantity ELSE 0 END) AS "PLAYERS AND ELECTRONICS",
    SUM(CASE WHEN department = 'PHARMACY RX' THEN quantity ELSE 0 END) AS "PHARMACY RX",
    SUM(CASE WHEN department = 'MENSWEAR' THEN quantity ELSE 0 END) AS MENSWEAR,
    SUM(CASE WHEN department = 'OPTICAL - FRAMES' THEN quantity ELSE 0 END) AS "OPTICAL - FRAMES",
    SUM(CASE WHEN department = 'SWIMWEAR/OUTERWEAR' THEN quantity ELSE 0 END) AS "SWIMWEAR/OUTERWEAR",
    SUM(CASE WHEN department = 'OTHER DEPARTMENTS' THEN quantity ELSE 0 END) AS "OTHER DEPARTMENTS",
    SUM(CASE WHEN department = 'MEDIA AND GAMING' THEN quantity ELSE 0 END) AS "MEDIA AND GAMING",
    SUM(CASE WHEN department = 'FURNITURE' THEN quantity ELSE 0 END) AS FURNITURE,
    SUM(CASE WHEN department = 'OPTICAL - LENSES' THEN quantity ELSE 0 END) AS "OPTICAL - LENSES",
    SUM(CASE WHEN department = 'SEASONAL' THEN quantity ELSE 0 END) AS SEASONAL,
    SUM(CASE WHEN department = 'LARGE HOUSEHOLD GOODS' THEN quantity ELSE 0 END) AS "LARGE HOUSEHOLD GOODS",
    SUM(CASE WHEN department = '1-HR PHOTO' THEN quantity ELSE 0 END) AS "1-HR PHOTO",
    SUM(CASE WHEN department = 'CONCEPT STORES' THEN quantity ELSE 0 END) AS "CONCEPT STORES",
    SUM(CASE WHEN department = 'HEALTH AND BEAUTY AIDS' THEN quantity ELSE 0 END) AS "HEALTH AND BEAUTY AIDS"
  FROM joined_data
  GROUP BY o_order_id
)

-- Step 5: 将聚合结果左连接，填充缺失值（使用 COALESCE 函数将 NULL 转为 0），同时对 trip_type 进行编码映射
-- 此处 trip_type 的编码映射遵循 Python 中：先将 label_range 按字符串排序，
-- 得到映射关系：12→0,15→1,18→2,19→3,20→4,21→5,22→6,23→7,24→8,25→9,26→10,
-- 27→11,28→12,29→13,3→14,30→15,31→16,32→17,33→18,34→19,35→20,36→21,37→22,38→23,
-- 39→24,4→25,40→26,41→27,42→28,43→29,44→30,5→31,6→32,7→33,8→34,9→35,999→36。
-- 同时过滤掉 trip_type = 14 的记录。
SELECT
  a.o_order_id,
  a.scan_count,
  a.scan_count_abs,
  COALESCE(wp.Monday, 0) AS Monday,
  COALESCE(wp.Tuesday, 0) AS Tuesday,
  COALESCE(wp.Wednesday, 0) AS Wednesday,
  COALESCE(wp.Thursday, 0) AS Thursday,
  COALESCE(wp.Friday, 0) AS Friday,
  COALESCE(wp.Saturday, 0) AS Saturday,
  COALESCE(wp.Sunday, 0) AS Sunday,
  COALESCE(dp."FINANCIAL SERVICES", 0) AS "FINANCIAL SERVICES",
  COALESCE(dp.SHOES, 0) AS SHOES,
  COALESCE(dp."PERSONAL CARE", 0) AS "PERSONAL CARE",
  COALESCE(dp."PAINT AND ACCESSORIES", 0) AS "PAINT AND ACCESSORIES",
  COALESCE(dp."DSD GROCERY", 0) AS "DSD GROCERY",
  COALESCE(dp."MEAT - FRESH & FROZEN", 0) AS "MEAT - FRESH & FROZEN",
  COALESCE(dp.DAIRY, 0) AS DAIRY,
  COALESCE(dp."PETS AND SUPPLIES", 0) AS "PETS AND SUPPLIES",
  COALESCE(dp."HOUSEHOLD CHEMICALS/SUPP", 0) AS "HOUSEHOLD CHEMICALS/SUPP",
  COALESCE(dp."IMPULSE MERCHANDISE", 0) AS "IMPULSE MERCHANDISE",
  COALESCE(dp.PRODUCE, 0) AS PRODUCE,
  COALESCE(dp."CANDY, TOBACCO, COOKIES", 0) AS "CANDY, TOBACCO, COOKIES",
  COALESCE(dp."GROCERY DRY GOODS", 0) AS "GROCERY DRY GOODS",
  COALESCE(dp."BOYS WEAR", 0) AS "BOYS WEAR",
  COALESCE(dp."FABRICS AND CRAFTS", 0) AS "FABRICS AND CRAFTS",
  COALESCE(dp."JEWELRY AND SUNGLASSES", 0) AS "JEWELRY AND SUNGLASSES",
  COALESCE(dp."MENS WEAR", 0) AS "MENS WEAR",
  COALESCE(dp.ACCESSORIES, 0) AS ACCESSORIES,
  COALESCE(dp."HOME MANAGEMENT", 0) AS "HOME MANAGEMENT",
  COALESCE(dp."FROZEN FOODS", 0) AS "FROZEN FOODS",
  COALESCE(dp."SERVICE DELI", 0) AS "SERVICE DELI",
  COALESCE(dp."INFANT CONSUMABLE HARDLINES", 0) AS "INFANT CONSUMABLE HARDLINES",
  COALESCE(dp."PRE PACKED DELI", 0) AS "PRE PACKED DELI",
  COALESCE(dp."COOK AND DINE", 0) AS "COOK AND DINE",
  COALESCE(dp."PHARMACY OTC", 0) AS "PHARMACY OTC",
  COALESCE(dp.LADIESWEAR, 0) AS LADIESWEAR,
  COALESCE(dp."COMM BREAD", 0) AS "COMM BREAD",
  COALESCE(dp.BAKERY, 0) AS BAKERY,
  COALESCE(dp."HOUSEHOLD PAPER GOODS", 0) AS "HOUSEHOLD PAPER GOODS",
  COALESCE(dp.CELEBRATION, 0) AS CELEBRATION,
  COALESCE(dp.HARDWARE, 0) AS HARDWARE,
  COALESCE(dp.BEAUTY, 0) AS BEAUTY,
  COALESCE(dp.AUTOMOTIVE, 0) AS AUTOMOTIVE,
  COALESCE(dp."BOOKS AND MAGAZINES", 0) AS "BOOKS AND MAGAZINES",
  COALESCE(dp.SEAFOOD, 0) AS SEAFOOD,
  COALESCE(dp."OFFICE SUPPLIES", 0) AS "OFFICE SUPPLIES",
  COALESCE(dp."LAWN AND GARDEN", 0) AS "LAWN AND GARDEN",
  COALESCE(dp."SHEER HOSIERY", 0) AS "SHEER HOSIERY",
  COALESCE(dp.WIRELESS, 0) AS WIRELESS,
  COALESCE(dp.BEDDING, 0) AS BEDDING,
  COALESCE(dp."BATH AND SHOWER", 0) AS "BATH AND SHOWER",
  COALESCE(dp."HORTICULTURE AND ACCESS", 0) AS "HORTICULTURE AND ACCESS",
  COALESCE(dp."HOME DECOR", 0) AS "HOME DECOR",
  COALESCE(dp.TOYS, 0) AS TOYS,
  COALESCE(dp."INFANT APPAREL", 0) AS "INFANT APPAREL",
  COALESCE(dp."LADIES SOCKS", 0) AS "LADIES SOCKS",
  COALESCE(dp."PLUS AND MATERNITY", 0) AS "PLUS AND MATERNITY",
  COALESCE(dp.ELECTRONICS, 0) AS ELECTRONICS,
  COALESCE(dp."GIRLS WEAR, 4-6X  AND 7-14", 0) AS "GIRLS WEAR, 4-6X  AND 7-14",
  COALESCE(dp."BRAS & SHAPEWEAR", 0) AS "BRAS & SHAPEWEAR",
  COALESCE(dp."LIQUOR,WINE,BEER", 0) AS "LIQUOR,WINE,BEER",
  COALESCE(dp."SLEEPWEAR/FOUNDATIONS", 0) AS "SLEEPWEAR/FOUNDATIONS",
  COALESCE(dp."CAMERAS AND SUPPLIES", 0) AS "CAMERAS AND SUPPLIES",
  COALESCE(dp."SPORTING GOODS", 0) AS "SPORTING GOODS",
  COALESCE(dp."PLAYERS AND ELECTRONICS", 0) AS "PLAYERS AND ELECTRONICS",
  COALESCE(dp."PHARMACY RX", 0) AS "PHARMACY RX",
  COALESCE(dp.MENSWEAR, 0) AS MENSWEAR,
  COALESCE(dp."OPTICAL - FRAMES", 0) AS "OPTICAL - FRAMES",
  COALESCE(dp."SWIMWEAR/OUTERWEAR", 0) AS "SWIMWEAR/OUTERWEAR",
  COALESCE(dp."OTHER DEPARTMENTS", 0) AS "OTHER DEPARTMENTS",
  COALESCE(dp."MEDIA AND GAMING", 0) AS "MEDIA AND GAMING",
  COALESCE(dp.FURNITURE, 0) AS FURNITURE,
  COALESCE(dp."OPTICAL - LENSES", 0) AS "OPTICAL - LENSES",
  COALESCE(dp.SEASONAL, 0) AS SEASONAL,
  COALESCE(dp."LARGE HOUSEHOLD GOODS", 0) AS "LARGE HOUSEHOLD GOODS",
  COALESCE(dp."1-HR PHOTO", 0) AS "1-HR PHOTO",
  COALESCE(dp."CONCEPT STORES", 0) AS "CONCEPT STORES",
  COALESCE(dp."HEALTH AND BEAUTY AIDS", 0) AS "HEALTH AND BEAUTY AIDS",
  -- 对 trip_type 进行编码映射（注意：先过滤掉 trip_type = 14 的记录）
  CASE 
    WHEN a.trip_type = 12 THEN 0
    WHEN a.trip_type = 15 THEN 1
    WHEN a.trip_type = 18 THEN 2
    WHEN a.trip_type = 19 THEN 3
    WHEN a.trip_type = 20 THEN 4
    WHEN a.trip_type = 21 THEN 5
    WHEN a.trip_type = 22 THEN 6
    WHEN a.trip_type = 23 THEN 7
    WHEN a.trip_type = 24 THEN 8
    WHEN a.trip_type = 25 THEN 9
    WHEN a.trip_type = 26 THEN 10
    WHEN a.trip_type = 27 THEN 11
    WHEN a.trip_type = 28 THEN 12
    WHEN a.trip_type = 29 THEN 13
    WHEN a.trip_type = 3 THEN 14
    WHEN a.trip_type = 30 THEN 15
    WHEN a.trip_type = 31 THEN 16
    WHEN a.trip_type = 32 THEN 17
    WHEN a.trip_type = 33 THEN 18
    WHEN a.trip_type = 34 THEN 19
    WHEN a.trip_type = 35 THEN 20
    WHEN a.trip_type = 36 THEN 21
    WHEN a.trip_type = 37 THEN 22
    WHEN a.trip_type = 38 THEN 23
    WHEN a.trip_type = 39 THEN 24
    WHEN a.trip_type = 4 THEN 25
    WHEN a.trip_type = 40 THEN 26
    WHEN a.trip_type = 41 THEN 27
    WHEN a.trip_type = 42 THEN 28
    WHEN a.trip_type = 43 THEN 29
    WHEN a.trip_type = 44 THEN 30
    WHEN a.trip_type = 5 THEN 31
    WHEN a.trip_type = 6 THEN 32
    WHEN a.trip_type = 7 THEN 33
    WHEN a.trip_type = 8 THEN 34
    WHEN a.trip_type = 9 THEN 35
    WHEN a.trip_type = 999 THEN 36
    ELSE -1
  END AS trip_type_encoded
FROM agg_counts a
LEFT JOIN weekday_pivot wp ON a.o_order_id = wp.o_order_id
LEFT JOIN dept_pivot dp ON a.o_order_id = dp.o_order_id
WHERE a.trip_type <> 14;


EXPLAIN ANALYZE
SELECT
    count(*)
FROM
    tpcai_uc08
WHERE
    predict (
        '/volumn/Retree_exp/workloads/tpcai-uc08/model/?.onnx',
    scan_count,
    scan_count_abs,
    Friday,
    Monday,
    Saturday,
    Sunday,
    Thursday,
    Tuesday,
    Wednesday,
    AUTOMOTIVE,
    BAKERY,
    SHEER_HOSIERY,
    OTHER_DEPARTMENTS,
    FURNITURE,
    SWIMWEAR_OUTERWEAR,
    OPTICAL__FRAMES,
    ACCESSORIES,
    MENSWEAR,
    LARGE_HOUSEHOLD_GOODS,
    PLUS_AND_MATERNITY,
    LADIES_SOCKS,
    CONCEPT_STORES,
    OPTICAL__LENSES,
    HR_PHOTO,
    BOOKS_AND_MAGAZINES,
    BRAS__SHAPEWEAR,
    PRE_PACKED_DELI,
    SEAFOOD,
    HEALTH_AND_BEAUTY_AIDS,
    SLEEPWEAR_FOUNDATIONS,
    SEASONAL,
    CAMERAS_AND_SUPPLIES,
    BATH_AND_SHOWER,
    BEAUTY,
    BEDDING,
    BOYS_WEAR,
    CANDY_TOBACCO_COOKIES,
    CELEBRATION,
    COMM_BREAD,
    COOK_AND_DINE,
    DAIRY,
    DSD_GROCERY,
    ELECTRONICS,
    FABRICS_AND_CRAFTS,
    FINANCIAL_SERVICES,
    FROZEN_FOODS,
    GIRLS_WEAR_46X__AND_714,
    GROCERY_DRY_GOODS,
    HARDWARE,
    HOME_DECOR,
    HOME_MANAGEMENT,
    HORTICULTURE_AND_ACCESS,
    HOUSEHOLD_CHEMICALS_SUPP,
    HOUSEHOLD_PAPER_GOODS,
    IMPULSE_MERCHANDISE,
    INFANT_APPAREL,
    INFANT_CONSUMABLE_HARDLINES,
    JEWELRY_AND_SUNGLASSES,
    LADIESWEAR,
    LAWN_AND_GARDEN,
    LIQUORWINEBEER,
    MEAT__FRESH__FROZEN,
    MEDIA_AND_GAMING,
    MENS_WEAR,
    OFFICE_SUPPLIES,
    PAINT_AND_ACCESSORIES,
    PERSONAL_CARE,
    PETS_AND_SUPPLIES,
    PHARMACY_OTC,
    PHARMACY_RX,
    PLAYERS_AND_ELECTRONICS,
    PRODUCE,
    SERVICE_DELI,
    SHOES,
    SPORTING_GOODS,
    TOYS,
    WIRELESS
    ) = ?;