CREATE TABLE hospital AS
SELECT * FROM read_csv('/volumn/Retree_exp/workloads/hospital/data-extension/?/hospital.csv', header=True, columns={
    'eid': 'INT64',
    'vdate': 'DATE',
    'rcount': 'VARCHAR',
    'gender': 'VARCHAR',
    'dialysisrenalendstage': 'INT64',
    'asthma': 'INT64',
    'irondef': 'INT64',
    'pneum': 'INT64',
    'substancedependence': 'INT64',
    'psychologicaldisordermajor': 'INT64',
    'depress': 'INT64',
    'psychother': 'INT64',
    'fibrosisandother': 'INT64',
    'malnutrition': 'INT64',
    'hemo': 'INT64',
    'hematocrit': 'FLOAT',
    'neutrophils': 'FLOAT',
    'sodium': 'FLOAT',
    'glucose': 'FLOAT',
    'bloodureanitro': 'FLOAT',
    'creatinine': 'FLOAT',
    'bmi': 'FLOAT',
    'pulse': 'FLOAT',
    'respiration': 'FLOAT',
    'secondarydiagnosisnonicd9': 'INT64',
    'discharged': 'DATE',
    'facid': 'VARCHAR'
});
